backfiller:
  path: interloper.SerialBackfiller
runner:
  path: interloper.MultiThreadRunner
destinations:
  file:
    path: interloper.FileDestination
    init:
      base_path: data
dag:
  assets:
    - type: source
      path: interloper_assets.DemoSource
