name: Check & Release

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".github/workflows/docs.yaml"
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        type: choice
        options:
          - stable
          - rc
        default: stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  release:
    uses: ./.github/workflows/_release.yaml
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'main'
    needs: checks
    with:
      release_type: ${{ inputs.release_type }}
    secrets:
      SEMANTIC_RELEASE_APP_ID: ${{ vars.SEMANTIC_RELEASE_APP_ID }}
      SEMANTIC_RELEASE_APP_KEY: ${{ secrets.SEMANTIC_RELEASE_APP_KEY }}
