name: Checks

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".github/workflows/docs.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    permissions:
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UV setup
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false
          python-version: ${{ matrix.python-version }}
          cache-suffix: "py${{ matrix.python-version }}"

      - name: UV sync
        run: uv sync --all-packages --all-extras

      - name: Ruff
        run: uv run ruff check .

      - name: Pyright
        run: uv run pyright

      - name: Pytest
        run: uv run pytest --cov --cov-report=xml

      - name: Upload coverage
        if: matrix.python-version == '3.12'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
