name: Check & Release

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".github/workflows/docs.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  release:
    uses: ./.github/workflows/_release.yaml
    if: github.ref_name == 'main' || github.ref_name == 'rc' || github.ref_name == 'dev'
    needs: checks
    secrets:
      SEMANTIC_RELEASE_APP_ID: ${{ vars.SEMANTIC_RELEASE_APP_ID }}
      SEMANTIC_RELEASE_APP_KEY: ${{ secrets.SEMANTIC_RELEASE_APP_KEY }}
